from dataclasses import dataclass
from typing import Any
import json


@dataclass
class ChartRecommendation:
    chart_type: str
    reason: str
    priority: int
    echarts_series_type: str


@dataclass
class RenderResult:
    chart_type: str
    html_path: str
    title: str
    record_count: int
    recommendation: ChartRecommendation


ECHARTS_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }}</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js"></script>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ background: #1a1a2e; color: #eee; font-family: 'Segoe UI', sans-serif; }}
  .header {{ padding: 20px 30px; background: linear-gradient(135deg, #16213e, #0f3460); }}
  .header h1 {{ font-size: 22px; font-weight: 600; }}
  .header .meta {{ font-size: 13px; color: #8899aa; margin-top: 4px; }}
  #chart {{ width: 100%; height: 520px; }}
  .footer {{ padding: 12px 30px; font-size: 12px; color: #556; text-align: center; }}
</style>
</head>
<body>
<div class="header">
  <h1>{{ title }}</h1>
  <div class="meta">{{ meta }}</div>
</div>
<div id="chart"></div>
<div class="footer">Generated by TeleAgent Visualization Renderer &middot; ECharts 5.5</div>
<script>
var chart = echarts.init(document.getElementById('chart'), 'dark');
var option = {{ option_json }};
chart.setOption(option);
window.addEventListener('resize', function() {{ chart.resize(); }});
</script>
</body>
</html>"""


class VisualizationRenderer:
    CHART_TYPES = {
        "bar": {"name": "柱状图", "series": "bar"},
        "line": {"name": "折线图", "series": "line"},
        "pie": {"name": "饼图", "series": "pie"},
        "scatter": {"name": "散点图", "series": "scatter"},
    }

    def __init__(self, output_dir: str = "."):
        self.output_dir = output_dir

    def render(
        self,
        data: list[dict],
        title: str = "数据可视化",
        category_field: str | None = None,
        value_fields: list[str] | None = None,
        preferred_type: str | None = None,
    ) -> RenderResult:
        if not data:
            raise ValueError("数据不能为空")
        analysis = self._analyze_data(data, category_field, value_fields)
        rec = self._recommend_chart(analysis, preferred_type)
        option = self._build_echarts_option(data, analysis, rec, title)
        html = self._render_html(title, analysis, option)
        filename = f"{self._safe_filename(title)}_{rec.chart_type}.html"
        html_path = self._write_file(filename, html)
        return RenderResult(
            chart_type=rec.chart_type,
            html_path=html_path,
            title=title,
            record_count=len(data),
            recommendation=rec,
        )

    def _analyze_data(self, data, category_field, value_fields) -> dict:
        sample = data[0]
        fields = list(sample.keys())
        numeric_fields = []
        text_fields = []
        for f in fields:
            vals = [r.get(f) for r in data if r.get(f) is not None]
            num_count = sum(1 for v in vals if isinstance(v, (int, float)))
            if num_count > len(vals) * 0.7:
                numeric_fields.append(f)
            else:
                text_fields.append(f)
        if category_field is None:
            category_field = text_fields[0] if text_fields else fields[0]
        if value_fields is None:
            value_fields = [f for f in numeric_fields if f != category_field][:3]
            if not value_fields and category_field in numeric_fields:
                value_fields = [f for f in numeric_fields if f != category_field][:3]
        cat_cardinality = len(set(r.get(category_field) for r in data))
        return {
            "fields": fields,
            "numeric_fields": numeric_fields,
            "text_fields": text_fields,
            "category_field": category_field,
            "value_fields": value_fields,
            "category_cardinality": cat_cardinality,
            "row_count": len(data),
        }

    def _recommend_chart(self, analysis: dict, preferred: str | None = None) -> ChartRecommendation:
        if preferred and preferred in self.CHART_TYPES:
            info = self.CHART_TYPES[preferred]
            return ChartRecommendation(
                chart_type=preferred,
                reason=f"用户指定{info['name']}",
                priority=1,
                echarts_series_type=info["series"],
            )
        n_cat = analysis["category_cardinality"]
        n_val = len(analysis["value_fields"])
        n_rows = analysis["row_count"]
        is_time = any(
            kw in analysis["category_field"].lower()
            for kw in ["month", "date", "time", "year", "period", "月份", "日期"]
        )
        candidates = []
        if is_time and n_rows > 3:
            candidates.append(
                ChartRecommendation("line", "时间序列数据，折线图展示趋势最佳", 1, "line")
            )
            candidates.append(
                ChartRecommendation("bar", "时间序列也可用柱状图进行对比", 2, "bar")
            )
        if n_cat <= 8 and n_val == 1 and not is_time:
            candidates.append(
                ChartRecommendation("pie", "类别少且单一数值，饼图展示占比最佳", 1, "pie")
            )
        if n_cat > 1 and n_val >= 1:
            candidates.append(
                ChartRecommendation("bar", "多类别数值对比，柱状图最直观", 1 if not is_time else 3, "bar")
            )
        if n_val >= 2 and n_rows > 5:
            candidates.append(
                ChartRecommendation("scatter", "多数值维度，散点图可揭示相关性", 2, "scatter")
            )
        if n_cat > 8:
            candidates = [
                c for c in candidates if c.chart_type != "pie"
            ]
            candidates.append(
                ChartRecommendation("bar", "类别较多，柱状图排序后更清晰", 2, "bar")
            )
        if not candidates:
            candidates.append(
                ChartRecommendation("bar", "默认推荐柱状图", 3, "bar")
            )
        candidates.sort(key=lambda c: c.priority)
        return candidates[0]

    def _build_echarts_option(self, data, analysis, rec, title) -> dict:
        cat_field = analysis["category_field"]
        val_fields = analysis["value_fields"]
        categories = [str(r.get(cat_field, "")) for r in data]
        series = []
        palette = [
            "#5470c6", "#91cc75", "#fac858", "#ee6666",
            "#73c0de", "#3ba272", "#fc8452", "#9a60b4",
        ]
        if rec.chart_type == "pie":
            first_val = val_fields[0] if val_fields else analysis["numeric_fields"][0]
            pie_data = []
            for i, r in enumerate(data):
                pie_data.append({
                    "name": str(r.get(cat_field, f"项{i}")),
                    "value": r.get(first_val, 0),
                    "itemStyle": {"color": palette[i % len(palette)]},
                })
            return {
                "tooltip": {"trigger": "item", "formatter": "{b}: {c} ({d}%)"},
                "legend": {"top": "5%", "left": "center", "textStyle": {"color": "#ccc"}},
                "series": [{
                    "type": "pie",
                    "radius": ["35%", "65%"],
                    "center": ["50%", "55%"],
                    "label": {"color": "#ccc", "formatter": "{b}\n{d}%"},
                    "data": pie_data,
                    "emphasis": {
                        "itemStyle": {
                            "shadowBlur": 10,
                            "shadowOffsetX": 0,
                            "shadowColor": "rgba(0,0,0,0.5)",
                        }
                    },
                }],
            }
        for idx, vf in enumerate(val_fields):
            values = [r.get(vf) for r in data]
            s: dict[str, Any] = {
                "name": vf,
                "type": rec.echarts_series_type,
                "data": values,
                "itemStyle": {"color": palette[idx % len(palette)]},
            }
            if rec.chart_type == "line":
                s["smooth"] = True
                s["lineStyle"] = {"width": 2.5}
                s["areaStyle"] = {"opacity": 0.15}
                s["symbol"] = "circle"
                s["symbolSize"] = 6
            elif rec.chart_type == "bar":
                s["barMaxWidth"] = 40
                s["label"] = {"show": len(data) <= 15, "position": "top", "color": "#aaa", "fontSize": 11}
            elif rec.chart_type == "scatter" and len(val_fields) >= 2 and idx == 0:
                xf, yf = val_fields[0], val_fields[1]
                scatter_data = [
                    [r.get(xf, 0), r.get(yf, 0)]
                    for r in data
                ]
                s["data"] = scatter_data
                s["symbolSize"] = 10
                s["name"] = f"{xf} vs {yf}"
            series.append(s)
        option: dict[str, Any] = {
            "tooltip": {"trigger": "axis", "backgroundColor": "rgba(0,0,0,0.7)", "textStyle": {"color": "#fff"}},
            "legend": {"top": "3%", "textStyle": {"color": "#ccc"}},
            "grid": {"top": "15%", "left": "8%", "right": "5%", "bottom": "12%", "containLabel": True},
            "xAxis": {
                "type": "category",
                "data": categories,
                "axisLabel": {"color": "#aaa", "rotate": len(categories) > 8 and 30 or 0},
                "axisLine": {"lineStyle": {"color": "#445"}},
            },
            "yAxis": {
                "type": "value",
                "axisLabel": {"color": "#aaa"},
                "splitLine": {"lineStyle": {"color": "#2a2a4a"}},
            },
            "series": series,
        }
        if rec.chart_type == "line" and len(data) > 6:
            option["dataZoom"] = [
                {"type": "inside", "start": 0, "end": 100},
                {"type": "slider", "start": 0, "end": 100, "bottom": "3%", "borderColor": "#445"},
            ]
        return option

    def _render_html(self, title: str, analysis: dict, option: dict) -> str:
        from jinja2 import Template
        meta = (
            f"{analysis['row_count']}条记录 | "
            f"维度: {analysis['category_field']} | "
            f"指标: {', '.join(analysis['value_fields'])}"
        )
        tmpl = Template(ECHARTS_TEMPLATE)
        return tmpl.render(
            title=title,
            meta=meta,
            option_json=json.dumps(option, ensure_ascii=False, indent=2),
        )

    def _safe_filename(self, title: str) -> str:
        import re
        name = re.sub(r'[^\w\u4e00-\u9fff]', '_', title)
        return name[:40] if len(name) > 40 else name

    def _write_file(self, filename: str, content: str) -> str:
        import os
        os.makedirs(self.output_dir, exist_ok=True)
        path = os.path.join(self.output_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return os.path.abspath(path)

    @staticmethod
    def format_report(result: RenderResult) -> str:
        rec = result.recommendation
        return (
            f"图表类型: {rec.chart_type} ({rec.reason})\n"
            f"数据行数: {result.record_count}\n"
            f"输出文件: {result.html_path}"
        )
